router

    .post(
        "/nft/auth/addNft",
        validators.nfts.addNftPayloadValidation,
        middlewares.validation.request,
        actions.nfts.update.addNft
    )
    .put(
        "/space/updateNft/:id",
        middlewares.id_validation.validateId,
        actions.nfts.update.updateNft
    )
    .get(
        "/nft/getAllNfts",
        actions.nfts.list.getAllNfts
    )
    .get(
        "/nft/getNFTBySearch/:term",
        middlewares.validation.request,
        actions.nfts.list.getNFTBySearch
    )
    .get(
        "/nft/getNftByToken/:id",
        validators.nfts.getNftByTokenPayloadValidation,
        actions.nfts.list.getNftByToken
    )
    .post(
        "/nft/getDataByURL",
        actions.nfts.list.getDataByURL
    )
    .get(
        "/nft/getNFTCount",
        actions.nfts.list.getNFTCount
    )
    .get(
        "/nft/getSoldSum",
        actions.nfts.list.getSoldSum
    )
    .get(
        "/nft/getNFTCountByRarity/:rarity",
        actions.nfts.list.getNFTCountByRarity
    )
    .get(
        "/nft/getSoldSumByRarity/:rarity",
        actions.nfts.list.getSoldSumByRarity
    )
    .get(
        "/nft/getCategories",
        actions.nfts.list.getCategories
    )
    .get(
        "/nft/getNFTsByCategory/:category",
        actions.nfts.list.getNFTsByCategory
    )
    .get(
        "/nft/getArchitectures",
        actions.nfts.list.getArchitectures
    );

module.exports = { prefix: "nft", router };